kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: ${DOCKER_USER}
    password: ${DOCKER_PASS}
    repo: ashokshingade24/caching
    tags:
      - latest
      - '1.0.1'
      - '1.0'
- name: deploy-to-heroku
  commands:
    - /bin/bash deploy_heroku.sh
